name: lint

on:
  push:
  pull_request:

jobs:
  golangci:
    name: Lint
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        go-version: [ "1.16" ]
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.36
          args: --timeout=5m
          only-new-issues: true
